/*
THE MAIN ISSUE WE INCOUNTER IS THAT WHEN WE ADD THE 5 PERSON SECOND TIME IT IS SHOWING THAT QUEUE IS FULL WHILE THERE IS ONLY 5 PERSON IN THE QUEUE AND HAVE 5 SPACE LEFT WHICH CANNOT ABLE TO USE AGAIN
*/